# One Hot Encoding - sklearn

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
data = {
    "sales": [
        100000,
        222000,
        1000000,
        522000,
        111111,
        222222,
        1111111,
        20000,
        75000,
        90000,
        1000000,
        10000,
    ],
    "city": [
        "Tampa",
        "Tampa",
        "Orlando",
        "Jacksonville",
        "Miami",
        "Jacksonville",
        "Miami",
        "Miami",
        "Orlando",
        "Orlando",
        "Orlando",
        "Orlando",
    ],
    "size": [
        "Small",
        "Medium",
        "Large",
        "Large",
        "Small",
        "Medium",
        "Large",
        "Small",
        "Medium",
        "Medium",
        "Medium",
        "Small",
    ],
}

In [3]:
df = pd.DataFrame(data=data)
df

      sales          city    size
0    100000         Tampa   Small
1    222000         Tampa  Medium
2   1000000       Orlando   Large
3    522000  Jacksonville   Large
4    111111         Miami   Small
5    222222  Jacksonville  Medium
6   1111111         Miami   Large
7     20000         Miami   Small
8     75000       Orlando  Medium
9     90000       Orlando  Medium
10  1000000       Orlando  Medium
11    10000       Orlando   Small

In [4]:
df["city"].unique()

<StringArray>
['Tampa', 'Orlando', 'Jacksonville', 'Miami']
Length: 4, dtype: str

# OneHotEncoder in Scikit-learn

`OneHotEncoder` is a preprocessing technique in **Scikit-learn** that converts categorical features into numerical binary columns (0/1). Machine learning algorithms generally cannot work directly with text categories, so OneHotEncoder transforms them into a machine-readable format.

---

## Parameters

| Parameter | Default Value | Description | Example |
|-----------|---------------|-------------|---------|
| `categories` | `'auto'` | Automatically detects unique categories from the input data. You can also specify categories manually. | `categories=[['Low', 'Medium', 'High']]` |
| `drop` | `None` | Drops one category per feature to avoid the dummy variable trap (multicollinearity). | `drop='first'`, `drop='if_binary'` |
| `sparse_output` | `True` | Returns a sparse matrix to save memory. Set to `False` to return a dense NumPy array. | `sparse_output=False` |
| `dtype` | `float` | Specifies the data type of the encoded output values. | `dtype=int`, `dtype=bool`, `dtype=float` |
| `handle_unknown` | `'error'` | Defines how to handle categories that were not seen during training when transforming new data. | `handle_unknown='ignore'` |
| `min_frequency` | `None` | Groups categories with low frequency into a single "infrequent" category. | `min_frequency=5` |
| `max_categories` | `None` | Limits the maximum number of encoded categories. Less frequent categories are grouped together. | `max_categories=10` |
| `feature_name_combiner` | `'concat'` | Controls how the output feature names are created. | `feature_name_combiner='concat'` |

---

### Explanation

- **`drop='first'`**
  - Removes the first category from each feature.

- **`handle_unknown='ignore'`**
  - Prevents errors when new unseen categories appear during prediction.
  - Encodes unknown categories as all zeros.

- **`sparse_output=False`**
  - Returns a normal NumPy array instead of a sparse matrix.

- **`dtype=int`**
  - Returns binary values as integers (`0` and `1`) instead of floating-point values (`0.0` and `1.0`).

---

# set_output(transform='pandas')

By default, `OneHotEncoder` returns a **NumPy array** after transformation.

Using:

```python
ohe = OneHotEncoder(
    sparse_output=False
).set_output(transform='pandas')
```

returns a **Pandas DataFrame** with meaningful column names.

In [5]:
ohe = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False,
).set_output(transform="pandas")

In [6]:
ohetransform_city = ohe.fit_transform(df[["city"]])
ohetransform_city

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [7]:
ohetransform_size = ohe.fit_transform(df[["size"]])
ohetransform_size

    size_Large  size_Medium  size_Small
0          0.0          0.0         1.0
1          0.0          1.0         0.0
2          1.0          0.0         0.0
3          1.0          0.0         0.0
4          0.0          0.0         1.0
5          0.0          1.0         0.0
6          1.0          0.0         0.0
7          0.0          0.0         1.0
8          0.0          1.0         0.0
9          0.0          1.0         0.0
10         0.0          1.0         0.0
11         0.0          0.0         1.0

In [8]:
df = pd.concat([df, ohetransform_city, ohetransform_size], axis=1)
df

,sales,city,size,city_Jacksonville,city_Miami,city_Orlando,city_Tampa,size_Large,size_Medium,size_Small
0,100000,Tampa,Small,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,222000,Tampa,Medium,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,1000000,Orlando,Large,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,522000,Jacksonville,Large,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,111111,Miami,Small,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5,222222,Jacksonville,Medium,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6,1111111,Miami,Large,0.0,1.0,0.0,0.0,1.0,0.0,0.0
7,20000,Miami,Small,0.0,1.0,0.0,0.0,0.0,0.0,1.0
8,75000,Orlando,Medium,0.0,0.0,1.0,0.0,0.0,1.0,0.0
9,90000,Orlando,Medium,0.0,0.0,1.0,0.0,0.0,1.0,0.0
10,1000000,Orlando,Medium,0.0,0.0,1.0,0.0,0.0,1.0,0.0
11,10000,Orlando,Small,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [9]:
df = df.drop(columns=["city", "size"])
df

,sales,city_Jacksonville,city_Miami,city_Orlando,city_Tampa,size_Large,size_Medium,size_Small
0,100000,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,222000,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,1000000,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,522000,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,111111,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5,222222,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6,1111111,0.0,1.0,0.0,0.0,1.0,0.0,0.0
7,20000,0.0,1.0,0.0,0.0,0.0,0.0,1.0
8,75000,0.0,0.0,1.0,0.0,0.0,1.0,0.0
9,90000,0.0,0.0,1.0,0.0,0.0,1.0,0.0
10,1000000,0.0,0.0,1.0,0.0,0.0,1.0,0.0
11,10000,0.0,0.0,1.0,0.0,0.0,0.0,1.0