In [56]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score

In [57]:
df = pd.read_csv("../data_set/purchased.csv")
df

      Country     Sex  Age  Salary Purchased
0  Bangladesh  Female   44   72000        No
1       India    Male   27   48000       Yes
2    Pakistan  Female   30   54000        No
3       India    Male   38   61000        No
4    Pakistan  Female   40   65000       Yes
5  Bangladesh    Male   35   58000       Yes
6       India  Female   25   52000        No
7  Bangladesh    Male   48   79000       Yes
8    Pakistan  Female   50   83000        No
9  Bangladesh    Male   37   67000       Yes

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Sex        10 non-null     str
 2   Age        10 non-null     int64
 3   Salary     10 non-null     int64
 4   Purchased  10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [59]:
label_encoder = LabelEncoder()
df["Purchased_encoded"] = label_encoder.fit_transform(df["Purchased"])
df = df.drop(columns=["Purchased"])
df

      Country     Sex  Age  Salary  Purchased_encoded
0  Bangladesh  Female   44   72000                  0
1       India    Male   27   48000                  1
2    Pakistan  Female   30   54000                  0
3       India    Male   38   61000                  0
4    Pakistan  Female   40   65000                  1
5  Bangladesh    Male   35   58000                  1
6       India  Female   25   52000                  0
7  Bangladesh    Male   48   79000                  1
8    Pakistan  Female   50   83000                  0
9  Bangladesh    Male   37   67000                  1

In [60]:
df["Country"].unique()

<StringArray>
['Bangladesh', 'India', 'Pakistan']
Length: 3, dtype: str

In [61]:
df["Sex"].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [62]:
X = df.drop(columns=["Purchased_encoded"])
X

      Country     Sex  Age  Salary
0  Bangladesh  Female   44   72000
1       India    Male   27   48000
2    Pakistan  Female   30   54000
3       India    Male   38   61000
4    Pakistan  Female   40   65000
5  Bangladesh    Male   35   58000
6       India  Female   25   52000
7  Bangladesh    Male   48   79000
8    Pakistan  Female   50   83000
9  Bangladesh    Male   37   67000

In [63]:
y = df["Purchased_encoded"]
y

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased_encoded, dtype: int64

In [64]:
X = pd.get_dummies(
    X,
    columns=["Country", "Sex"],
)
X

,Age,Salary,Country_Bangladesh,Country_India,Country_Pakistan,Sex_Female,Sex_Male
0,44,72000,True,False,False,True,False
1,27,48000,False,True,False,False,True
2,30,54000,False,False,True,True,False
3,38,61000,False,True,False,False,True
4,40,65000,False,False,True,True,False
5,35,58000,True,False,False,False,True
6,25,52000,False,True,False,True,False
7,48,79000,True,False,False,False,True
8,50,83000,False,False,True,True,False
9,37,67000,True,False,False,False,True

# Perform PCA

In [65]:
pca_full = PCA()
pca_full.fit(X)
pca_full.explained_variance_ratio_

array([9.99999959e-01, 3.23243251e-08, 5.52594935e-09, 1.77975036e-09,
       9.17153161e-10, 6.25434062e-42, 1.18219155e-42])

In [66]:
np.cumsum(pca_full.explained_variance_ratio_ * 100)

array([ 99.99999595,  99.99999918,  99.99999973,  99.99999991,
       100.        , 100.        , 100.        ])

In [67]:
pca_99 = PCA(n_components=2)
X_pca = pca_99.fit_transform(X)
X_pca

array([[ 8.10000266e+03,  7.81386409e-01],
       [-1.59000034e+04,  9.27936440e-01],
       [-9.90000274e+03, -4.50784001e-01],
       [-2.89999888e+03,  2.70497003e+00],
       [ 1.10000158e+03,  1.74110702e+00],
       [-5.90000021e+03,  1.84895986e+00],
       [-1.19000058e+04, -4.03015904e+00],
       [ 1.51000037e+04, -2.17059947e-02],
       [ 1.91000041e+04, -9.98474991e-01],
       [ 3.09999895e+03, -2.50323573e+00]])

In [68]:
X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y, test_size=0.3, random_state=42
)
print("X_train")
print(X_train.shape)
print("X_test")
print(X_test.shape)
print("y_train")
print(y_train.shape)
print("y_test")
print(y_test.shape)

X_train
(7, 2)
X_test
(3, 2)
y_train
(7,)
y_test
(3,)

In [69]:
model = LinearRegression()
model.fit(X_train, y_train)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 0.401180701414688
Coefficients: [ 3.71376721e-05 -5.14295429e-02]

In [70]:
predictions = model.predict(X_test)

print(predictions)

[ 1.1618615  -0.23703176  0.08697727]