# Feature Engineering - OneHot Encoding

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

In [24]:
data = pd.read_csv("../data_set/Data_01.csv")
data

      Country     Sex  Age  Salary Purchased
0  Bangladesh  Female   44   72000        No
1       India    Male   27   48000       Yes
2    Pakistan  Female   30   54000        No
3       India    Male   38   61000        No
4    Pakistan  Female   40   65000       Yes
5  Bangladesh    Male   35   58000       Yes
6       India  Female   25   52000        No
7  Bangladesh    Male   48   79000       Yes
8    Pakistan  Female   50   83000        No
9  Bangladesh    Male   37   67000       Yes

In [25]:
le = LabelEncoder()
data["class"] = le.fit_transform(data.Purchased)
data

      Country     Sex  Age  Salary Purchased  class
0  Bangladesh  Female   44   72000        No      0
1       India    Male   27   48000       Yes      1
2    Pakistan  Female   30   54000        No      0
3       India    Male   38   61000        No      0
4    Pakistan  Female   40   65000       Yes      1
5  Bangladesh    Male   35   58000       Yes      1
6       India  Female   25   52000        No      0
7  Bangladesh    Male   48   79000       Yes      1
8    Pakistan  Female   50   83000        No      0
9  Bangladesh    Male   37   67000       Yes      1

In [26]:
data = data.drop(columns="Purchased")
data

      Country     Sex  Age  Salary  class
0  Bangladesh  Female   44   72000      0
1       India    Male   27   48000      1
2    Pakistan  Female   30   54000      0
3       India    Male   38   61000      0
4    Pakistan  Female   40   65000      1
5  Bangladesh    Male   35   58000      1
6       India  Female   25   52000      0
7  Bangladesh    Male   48   79000      1
8    Pakistan  Female   50   83000      0
9  Bangladesh    Male   37   67000      1

In [27]:
# categorical data
cat_cols = ["Country", "Sex"]

## `pd.get_dummies()` is a Pandas function that converts categorical variables into numerical (binary) columns. This process is called One-Hot Encoding.

In [28]:
df = pd.get_dummies(data, columns=cat_cols)
df

,Age,Salary,class,Country_Bangladesh,Country_India,Country_Pakistan,Sex_Female,Sex_Male
0,44,72000,0,True,False,False,True,False
1,27,48000,1,False,True,False,False,True
2,30,54000,0,False,False,True,True,False
3,38,61000,0,False,True,False,False,True
4,40,65000,1,False,False,True,True,False
5,35,58000,1,True,False,False,False,True
6,25,52000,0,False,True,False,True,False
7,48,79000,1,True,False,False,False,True
8,50,83000,0,False,False,True,True,False
9,37,67000,1,True,False,False,False,True

In [29]:
df = df.drop(columns=["Country_Bangladesh", "Sex_Female"])
df

   Age  Salary  class  Country_India  Country_Pakistan  Sex_Male
0   44   72000      0          False             False     False
1   27   48000      1           True             False      True
2   30   54000      0          False              True     False
3   38   61000      0           True             False      True
4   40   65000      1          False              True     False
5   35   58000      1          False             False      True
6   25   52000      0           True             False     False
7   48   79000      1          False             False      True
8   50   83000      0          False              True     False
9   37   67000      1          False             False      True

In [30]:
X = df.drop("class", axis=1)  # Feature Matrix
X

   Age  Salary  Country_India  Country_Pakistan  Sex_Male
0   44   72000          False             False     False
1   27   48000           True             False      True
2   30   54000          False              True     False
3   38   61000           True             False      True
4   40   65000          False              True     False
5   35   58000          False             False      True
6   25   52000           True             False     False
7   48   79000          False             False      True
8   50   83000          False              True     False
9   37   67000          False             False      True

In [31]:
y = df["class"]
y

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: class, dtype: int64