# Cross Validations Techniques

In [46]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import ShuffleSplit
from sklearn.tree import DecisionTreeClassifier

In [47]:
df = pd.read_csv("../data_set/Data_Data.csv")
df.head()

      Country     Sex  Age  Salary Purchased
0  Bangladesh  Female   44   72000        No
1       India    Male   27   48000       Yes
2    Pakistan  Female   30   54000        No
3       India    Male   38   61000        No
4    Pakistan  Female   40   65000       Yes

In [48]:
df.isnull().sum()

Country      0
Sex          0
Age          0
Salary       0
Purchased    0
dtype: int64

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Sex        10 non-null     str
 2   Age        10 non-null     int64
 3   Salary     10 non-null     int64
 4   Purchased  10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [50]:
label_encoder = LabelEncoder()
df["Purchased_encoded"] = label_encoder.fit_transform(df["Purchased"])
df = df.drop(columns=["Purchased"])
df

      Country     Sex  Age  Salary  Purchased_encoded
0  Bangladesh  Female   44   72000                  0
1       India    Male   27   48000                  1
2    Pakistan  Female   30   54000                  0
3       India    Male   38   61000                  0
4    Pakistan  Female   40   65000                  1
5  Bangladesh    Male   35   58000                  1
6       India  Female   25   52000                  0
7  Bangladesh    Male   48   79000                  1
8    Pakistan  Female   50   83000                  0
9  Bangladesh    Male   37   67000                  1

In [51]:
X = df.drop(columns=["Purchased_encoded"])
X

      Country     Sex  Age  Salary
0  Bangladesh  Female   44   72000
1       India    Male   27   48000
2    Pakistan  Female   30   54000
3       India    Male   38   61000
4    Pakistan  Female   40   65000
5  Bangladesh    Male   35   58000
6       India  Female   25   52000
7  Bangladesh    Male   48   79000
8    Pakistan  Female   50   83000
9  Bangladesh    Male   37   67000

In [52]:
y = df["Purchased_encoded"]
y

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased_encoded, dtype: int64

In [53]:
X = pd.get_dummies(
    X,
    columns=["Country", "Sex"],
)
X

,Age,Salary,Country_Bangladesh,Country_India,Country_Pakistan,Sex_Female,Sex_Male
0,44,72000,True,False,False,True,False
1,27,48000,False,True,False,False,True
2,30,54000,False,False,True,True,False
3,38,61000,False,True,False,False,True
4,40,65000,False,False,True,True,False
5,35,58000,True,False,False,False,True
6,25,52000,False,True,False,True,False
7,48,79000,True,False,False,False,True
8,50,83000,False,False,True,True,False
9,37,67000,True,False,False,False,True

In [54]:
y.value_counts()

Purchased_encoded
0    5
1    5
Name: count, dtype: int64

### HoldOut Validation Approach- Train And Test Split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [56]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
result = model.score(X_test, y_test)
print(result)

0.0

### K Fold Cross Validation

In [57]:
kfold_validation = KFold(3)
model = DecisionTreeClassifier()

In [58]:
result = cross_val_score(model, X, y, cv=kfold_validation)
print(result)

[0.25       0.66666667 0.66666667]

In [59]:
print(np.mean(result))

0.5277777777777778

### Stratified K-fold Cross Validation

In [60]:
skfold = StratifiedKFold(n_splits=3)
model = DecisionTreeClassifier()
scores = cross_val_score(model, X, y, cv=skfold)
print(scores)

[0.25       0.66666667 0.        ]

In [61]:
print(np.mean(scores))

0.3055555555555555

### Leave One Out Cross Validation(LOOCV)

In [62]:
model = DecisionTreeClassifier()
leave_validation = LeaveOneOut()
result = cross_val_score(model, X, y, cv=leave_validation)
print(result)

[0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]

In [63]:
print(np.mean(result))

0.3

### Repeated Random Test-Train Splits
This technique is a hybrid of traditional train-test splitting and the k-fold cross-validation method. In this technique, we create random splits of the data in the training-test set manner and then repeat the process of splitting and evaluating the algorithm multiple times, just like the cross-validation method.

In [64]:
model = DecisionTreeClassifier()
ssplit = ShuffleSplit(n_splits=10, test_size=0.3, random_state=42)
result = cross_val_score(model, X, y, cv=ssplit)
print(result)

[0.33333333 0.         0.66666667 0.33333333 0.33333333 0.66666667
 0.33333333 0.33333333 0.33333333 0.33333333]

In [65]:
print(np.mean(result))

0.3666666666666667