# Cross Validations Techniques

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import ShuffleSplit
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv("../data_set/iris_iris.csv")
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [3]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
class                0
dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   class              150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [5]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [8]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [9]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [11]:
y.value_counts()

class
0    50
1    50
2    50
Name: count, dtype: int64

### HoldOut Validation Approach- Train And Test Split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [13]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
result = model.score(X_test, y_test)
print(result)

1.0

### K Fold Cross Validation

In [14]:
kfold_validation = KFold(10)
model = DecisionTreeClassifier()

In [28]:
result = cross_val_score(model, X, y, cv=kfold_validation)
print(result)

[0.9122807  0.9122807  0.89473684 0.96491228 0.89473684 0.96491228
 0.89473684 0.94736842 0.94736842 0.91071429]

In [15]:
print(np.mean(result))

1.0

### Stratified K-fold Cross Validation

In [16]:
skfold = StratifiedKFold(n_splits=10)
model = DecisionTreeClassifier()
scores = cross_val_score(model, X, y, cv=skfold)
print(scores)

[1.         0.93333333 1.         0.93333333 0.93333333 0.86666667
 0.93333333 0.93333333 1.         1.        ]

In [17]:
print(np.mean(scores))

0.9533333333333334

### Leave One Out Cross Validation(LOOCV)

In [18]:
model = DecisionTreeClassifier()
leave_validation = LeaveOneOut()
result = cross_val_score(model, X, y, cv=leave_validation)
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]

In [19]:
print(np.mean(result))

0.9466666666666667

### Repeated Random Test-Train Splits
This technique is a hybrid of traditional train-test splitting and the k-fold cross-validation method. In this technique, we create random splits of the data in the training-test set manner and then repeat the process of splitting and evaluating the algorithm multiple times, just like the cross-validation method.

In [20]:
model = DecisionTreeClassifier()
ssplit = ShuffleSplit(n_splits=10, test_size=0.3, random_state=42)
result = cross_val_score(model, X, y, cv=ssplit)
print(result)

[1.         0.97777778 0.88888889 0.95555556 0.88888889 0.97777778
 0.91111111 0.91111111 1.         0.86666667]

In [21]:
print(np.mean(result))

0.9377777777777778