In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data_set/hiring.csv")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
# Rename columns
df = df.rename(
    columns={
        "experience": "Experience",
        "test_score(out of 10)": "Test_Score",
        "interview_score(out of 10)": "Interview_Score",
        "salary($)": "Salary",
    }
)
df

  Experience  Test_Score  Interview_Score  Salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [4]:
df.Experience = df.Experience.fillna("zero")
df

  Experience  Test_Score  Interview_Score  Salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [5]:
df.Test_Score = df.Test_Score.fillna(df.Test_Score.median())
df

  Experience  Test_Score  Interview_Score  Salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [6]:
X = pd.get_dummies(
    df[["Experience", "Test_Score", "Interview_Score"]],
    columns=["Experience"],
    drop_first=True,
)
X

,Test_Score,Interview_Score,Experience_five,Experience_seven,Experience_ten,Experience_three,Experience_two,Experience_zero
0,8.0,9,False,False,False,False,False,True
1,8.0,6,False,False,False,False,False,True
2,6.0,7,True,False,False,False,False,False
3,10.0,10,False,False,False,False,True,False
4,9.0,6,False,True,False,False,False,False
5,7.0,10,False,False,False,True,False,False
6,8.0,7,False,False,True,False,False,False
7,7.0,8,False,False,False,False,False,False

In [7]:
y = df["Salary"]
print(y)

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: Salary, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)
print("X_train")
print(X_train)
print("X_test")
print(X_test)
print("y_train")
print(y_train)
print("y_test")
print(y_test)

X_train
   Test_Score  Interview_Score  Experience_five  Experience_seven  \
7         7.0                8            False             False
2         6.0                7             True             False
4         9.0                6            False              True
3        10.0               10            False             False
6         8.0                7            False             False

   Experience_ten  Experience_three  Experience_two  Experience_zero
7           False             False           False            False
2           False             False           False            False
4           False             False           False            False
3           False             False            True            False
6            True             False           False            False
X_test
   Test_Score  Interview_Score  Experience_five  Experience_seven  \
1         8.0                6            False             False
5         7.0               10            False             False
0         8.0                9            False             False

   Experience_ten  Experience_three  Experience_two  Experience_zero
1           False             False           False             True
5           False              True           False            False
0           False             False           False             True
y_train
7    80000
2    60000
4    70000
3    65000
6    72000
Name: Salary, dtype: int64
y_test
1    45000
5    62000
0    50000
Name: Salary, dtype: int64

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 86866.27906976745
Coefficients: [ -3598.8372093    2290.69767442 -21308.13953488   1779.06976744
  -2110.46511628      0.          -8784.88372093      0.        ]

In [10]:
predictions = model.predict(X_test)

print(predictions)

[71819.76744186 84581.39534884 78691.86046512]

In [11]:
import pandas as pd

new_data = pd.DataFrame(
    {
        "Test_Score": [9],
        "Interview_Score": [6],
        "Experience_five": [0],
        "Experience_seven": [0],
        "Experience_ten": [0],
        "Experience_three": [0],
        "Experience_two": [2],
        "Experience_zero": [0],
    }
)

salary = model.predict(new_data)

print(salary)

[50651.1627907]